// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace NorthToBindingListWinForms.Models
{
    public partial class Contacts
    {
        public int ContactId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int? ContactTypeIdentifier { get; set; }
        public string Title => ContactTypeNavigation.ContactTitle;
        public virtual ContactType ContactTypeNavigation { get; set; }
    }
}