// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel;

namespace NorthToBindingListWinForms.Models
{
    public partial class ContactType
    {
        public ContactType()
        {
            //Contacts = new HashSet<Contacts>();
            Contacts = new BindingList<Contacts>();
        }

        public int ContactTypeIdentifier { get; set; }
        public string ContactTitle { get; set; }

        public virtual BindingList<Contacts> Contacts { get; set; }
    }
}