// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using MaxLengthApp.Models;
using Microsoft.EntityFrameworkCore;

namespace MaxLengthApp.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<ContactTypes> ContactTypes { get; set; }

    public virtual DbSet<Customer> Customer { get; set; }

    public virtual DbSet<Genders> Genders { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=.\\SQLEXPRESS;Initial Catalog=CustomerDatabase1;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasOne(d => d.ContactTypeIdentifierNavigation).WithMany(p => p.Customer).HasConstraintName("FK_Customer_ContactTypes");

            entity.HasOne(d => d.GenderIdentifierNavigation).WithMany(p => p.Customer).HasConstraintName("FK_Customer_Genders");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}