// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using SqlLiteSimpleApp1.OtherModels;

namespace SqlLiteSimpleApp1.Data1;

public partial class SampleContect : DbContext
{
    public SampleContect()
    {
    }

    public SampleContect(DbContextOptions<SampleContect> options)
        : base(options)
    {
    }

    public virtual DbSet<Person> Person { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlite("Data Source=C:\\OED\\DotnetLand\\VS2022\\EntityFrameworkCoreTips\\SqlLiteSimpleApp1\\Sample1.db");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>(entity =>
        {
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasColumnType("TEXT (50)");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasColumnType("TEXT (50)");
            entity.Property(e => e.Pin).HasColumnType("INTEGER (5)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}