// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using NorthWind2020ConsoleAppCore7.Data;

#pragma warning disable 219, 612, 618
#nullable enable

namespace NorthWind2020ConsoleAppCore7.Compiled
{
    [DbContext(typeof(Context))]
    public partial class ContextModel : RuntimeModel
    {
        static ContextModel()
        {
            var model = new ContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static ContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
