// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SqlLiteSimpleApp1.OtherModels;

public partial class Person
{
    public long Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public long? Pin { get; set; }
}